Created the create account panel
sambutler1017/software-engineering-26 pull request #7
Opened 2021-04-03 23:23 UTC by Jramos8

Added the functionality for the cancel button to return to the main login panel.

2021-04-03 23:40 UTC, sambutler1017 commented
Need to pull in master

2021-04-04 00:46 UTC, sambutler1017 requested changes

2021-04-04 00:46 UTC, sambutler1017 commented on Airline_Project_Group_26/BaseForm.Designer.cs
> -            this.profile_icon_navbar = new System.Windows.Forms.PictureBox();
Here. There is where you deleted the profile icon

2021-04-04 02:29 UTC, sambutler1017 requested changes

2021-04-04 02:29 UTC, sambutler1017 commented on Airline_Project_Group_26/BaseForm.Designer.cs
> -            this.profile_icon_navbar.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
This also needs added back in

2021-04-05 17:19 UTC, sambutler1017 requested changes

2021-04-05 17:19 UTC, sambutler1017 commented on Airline_Project_Group_26/BaseForm.cs
> +        private void cancel_button_Click(object sender, EventArgs e) => createAccountPanel.onCancelClick();
These are java docs. Look at the method above for document commenting.

2021-04-07 00:57 UTC, ischank1 approved these changes

2021-04-07 02:44 UTC, cheng801 approved these changes

2021-04-07 14:52 UTC, merged